spring:
  application:
    name: kafka-connect-monitoring-service
  data:
    redis:
      host: redis-12807.c73.us-east-1-2.ec2.redns.redis-cloud.com
      port: 12807
      password: x5mSZvZtFof9dg6TcOanszQyqq9YyEX2
      database: 0




monitoring:
  cpu-threshold: 10  # in percentage
  ram-threshold: 100  # in MB
  kafka-instances:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:3003
  cron: "0 */5 * * * ?" # mỗi 5 phút

  fm:
    url: http://172.16.28.194:8083/fm
    ne: EMS
    neIp: 1
    alarmId: 1001
    internalService: Kafka-connect-status

